INSERT INTO blogful (title, content, date_published)
VALUES 
('Does the World Still Need Pok Pok?',
'Says Andy Ricker, a white guy famously making Thai food: “Unless you’re not fucking paying attention, you have got to be having this thought.”',
'6/16/2020 at 6:00am'),
('Can White Portland’s Fragility Handle a Megaquake?',
'Nope. But here we are anyway.',
'6/16/2020 '),
('The Best Places to Work 2020',
'https://www.pdxmonthly.com/best-of-the-city/the-best-places-to-work-2020',
'12/31/2019'),
('Personalized Takeout Keeps the Essence of Portland Food Life Alive',
'Through hell and high water, Nodoguro, Coquine, and Gado Gado have morphed into makeshift takeout hot spots.',
'6/16/2020 at 5:00am'),
('The Food Scene’s New Rallying Cry: Improvise, Adapt, Overcome',
'https://www.pdxmonthly.com/eat-and-drink/2020/06/the-food-scene-s-new-rallying-cry-improvise-adapt-overcome',
'6/16/2020 at 5:00am'),
('Portland’s Best New Bars of 2020',
'https://www.pdxmonthly.com/eat-and-drink/portland-s-best-new-bars-of-2020',
'02/25/2020'),
('https://www.pdxmonthly.com/news-and-city-life/2019/12/befunky-s-portland-headquarters-is-a-gorgeous-minimalist-oasis',
'https://www.pdxmonthly.com/best-of-the-city/the-best-places-to-work-2020',
'12/31/2019 at 3:34pm'),
('Squarespace’s Downtown Office Puts an Emphasis on Togetherness—and Food',
'https://www.pdxmonthly.com/home-and-real-estate/2019/12/squarespace-s-downtown-office-puts-an-emphasis-on-togetherness-and-food',
'12/31/2019 at 3:34pm'),
('Expensify Infuses a Cold, Cavernous Former Downtown Bank with Life—and Dogs',
'https://www.pdxmonthly.com/news-and-city-life/2019/12/expensify-infuses-a-cavernous-former-downtown-bank-with-life-and-dogs',
'12/31/2019 at 3:33pm'),
("Software Giant Autodesk's Central Eastside Office Is an Homage to Portland Makers",
'https://www.pdxmonthly.com/news-and-city-life/2019/12/software-giant-autodesk-s-central-eastside-office-is-an-homage-to-portland-makers',
'12/31/2019 at 3:33pm'),
('12 Amazing Side Perks for Portland Workers',
'https://www.pdxmonthly.com/news-and-city-life/2019/12/12-amazing-side-perks-for-portland-workers',
'12/31/2019 at 3:34pm'),
('Paid Family Leave Finally Lands in Oregon',
'https://www.pdxmonthly.com/news-and-city-life/2019/12/paid-family-leave-finally-lands-in-oregon',
'12/31/2019 at 3:35pm'),
('Diversity in the Workplace: Who Is Doing It Right?',
'https://www.pdxmonthly.com/news-and-city-life/2019/12/diversity-in-the-workplace-who-is-doing-it-right',
'12/31/2019 at 3:29pm'),
('How to Switch Careers—According to these Portland Experts',
'https://www.pdxmonthly.com/news-and-city-life/2020/01/how-to-switch-careers-according-to-these-portland-experts',
'1/2/2020 at 11:11am'),
('Why You Should Always Love Your Work Family',
'https://www.pdxmonthly.com/news-and-city-life/2019/12/why-you-should-love-your-work-family',
'12/31/2019 at 3:29pm'),
('Best of the City 2016: Seven Essential Outdoor Escapes in Portland',
'https://www.pdxmonthly.com/travel-and-outdoors/2016/06/best-of-the-city-2016-seven-essential-outdoor-escapes-in-portland',
'6/13/2016 at 8:02am'),
('Best of the City 2016: 11 of Portland’s Most Stylish Things',
'https://www.pdxmonthly.com/style-and-shopping/2016/06/best-of-the-city-2016-11-of-portland-s-most-stylish-things',
'6/13/2016 at 8:00am'),
('Portland Hoods You Should Know',
'https://www.pdxmonthly.com/home-and-real-estate/2020/04/portland-hoods-you-should-know',
'4/1/2020 at 2:53pm '),
('The Ultimate Portland Shopping Cheat Sheet',
'pdxmonthly.com/style-and-shopping/2019/11/the-ultimate-portland-shopping-cheat-sheet',
'11/26/2019 at 2:08pm'),
('https://www.pdxmonthly.com/style-and-shopping/2019/11/the-ultimate-portland-shopping-cheat-sheet',
'https://www.pdxmonthly.com/style-and-shopping/2019/11/the-ultimate-portland-shopping-cheat-sheet',
'11/26/2019 at 2:08pm');